/**
 *
 * This file is autogenerated by runScript.sh
 * Creates image file name resources
 *
 */



#ifndef S_ICON_ITEM_FAVORITE_HIGHLIGHT
    #define S_ICON_ITEM_FAVORITE_HIGHLIGHT @"icon_item_favorite_highlight"
#endif

#ifndef S_ENTRIES
    #define S_ENTRIES @"entries"
#endif

#ifndef S_POST_HIGHLIGHT
    #define S_POST_HIGHLIGHT @"post_highlight"
#endif

#ifndef S_FM_MESSAGE_CHAT_LEFT_BG
    #define S_FM_MESSAGE_CHAT_LEFT_BG @"fm_message_chat_left_bg"
#endif

#ifndef S_STAR_ICON2_HIGHLIGHT
    #define S_STAR_ICON2_HIGHLIGHT @"star_icon2_highlight"
#endif

#ifndef S_MYCITY_NORMAL
    #define S_MYCITY_NORMAL @"mycity_normal"
#endif

#ifndef S_FEEDBACK_OUTGOING_BUBBLE
    #define S_FEEDBACK_OUTGOING_BUBBLE @"feedback_outgoing_bubble"
#endif

#ifndef S_ALL-WCPROPS
    #define S_ALL-WCPROPS @"all-wcprops"
#endif

#ifndef S_MYCITY_HIGHLIGHT
    #define S_MYCITY_HIGHLIGHT @"mycity_highlight"
#endif

#ifndef S_POST_NORMAL
    #define S_POST_NORMAL @"post_normal"
#endif

#ifndef S_HOME_HIGHLIGHT
    #define S_HOME_HIGHLIGHT @"home_highlight"
#endif

#ifndef S_BTN_ACCOUNT_BACK
    #define S_BTN_ACCOUNT_BACK @"btn_account_back"
#endif

#ifndef S_STAR_ICON2
    #define S_STAR_ICON2 @"star_icon2"
#endif

#ifndef S_ACCOUNT_HIGHLIGHT
    #define S_ACCOUNT_HIGHLIGHT @"account_highlight"
#endif

#ifndef S_FM_MESSAGE_CHAT_RIGHT_BG
    #define S_FM_MESSAGE_CHAT_RIGHT_BG @"fm_message_chat_right_bg"
#endif

#ifndef S_MESSAGE_HIGHLIGHT
    #define S_MESSAGE_HIGHLIGHT @"message_highlight"
#endif

#ifndef S_TRADE_DETAIL_PROGRESS_BAR_3
    #define S_TRADE_DETAIL_PROGRESS_BAR_3 @"trade_detail_progress_bar_3"
#endif

#ifndef S_TRADE_DETAIL_LOGISTIC_ICON
    #define S_TRADE_DETAIL_LOGISTIC_ICON @"trade_detail_logistic_icon"
#endif

#ifndef S_FISH_HIGHLIGHT
    #define S_FISH_HIGHLIGHT @"fish_highlight"
#endif

#ifndef S_ICON_ITEM_FAVORITE
    #define S_ICON_ITEM_FAVORITE @"icon_item_favorite"
#endif

#ifndef S_HOME_COLLECT
    #define S_HOME_COLLECT @"home_collect"
#endif

#ifndef S_TRADE_DETAIL_PROGRESS_BAR_1
    #define S_TRADE_DETAIL_PROGRESS_BAR_1 @"trade_detail_progress_bar_1"
#endif

#ifndef S_TRADE_DETAIL_PROGRESS_BAR_2
    #define S_TRADE_DETAIL_PROGRESS_BAR_2 @"trade_detail_progress_bar_2"
#endif

#ifndef S_HOME_COLLECTED
    #define S_HOME_COLLECTED @"home_collected"
#endif

#ifndef S_ACTIVE
    #define S_ACTIVE @"active"
#endif

#ifndef S_ALBUM_SELECTED
    #define S_ALBUM_SELECTED @"album_selected"
#endif

#ifndef S_ACCOUNT_NORMAL
    #define S_ACCOUNT_NORMAL @"account_normal"
#endif

#ifndef S_TRADE_DETAIL_PROGRESS_BAR_4
    #define S_TRADE_DETAIL_PROGRESS_BAR_4 @"trade_detail_progress_bar_4"
#endif

#ifndef S_HOME_NORMAL
    #define S_HOME_NORMAL @"home_normal"
#endif

#ifndef S_ACCOUNT_SELLING_ITEM_INVALID
    #define S_ACCOUNT_SELLING_ITEM_INVALID @"account_selling_item_invalid"
#endif

#ifndef S_MESSAGE_NORMAL
    #define S_MESSAGE_NORMAL @"message_normal"
#endif

#ifndef S_BG_MESSAGE_UNREAD
    #define S_BG_MESSAGE_UNREAD @"bg_message_unread"
#endif

#ifndef S_ITEM_COMMENT_TEXTVIEW_BG
    #define S_ITEM_COMMENT_TEXTVIEW_BG @"item_comment_textview_bg"
#endif

#ifndef S_FISH_NORMAL
    #define S_FISH_NORMAL @"fish_normal"
#endif

#ifndef S_TRADE_DETAIL_PROGRESS_BAR
    #define S_TRADE_DETAIL_PROGRESS_BAR @"trade_detail_progress_bar"
#endif

#ifndef S_REWORK
    #define S_REWORK @"rework"
#endif

