#!/usr/bin/python
#encoding:utf-8

import sys
import os

def imgfilenames(dic, path):
	for item in os.listdir(path):
		itemPath = os.path.join(path, item)
		if os.path.isfile(itemPath):
			nameComp = item.split('.')
			name = ''
			subfix = ''
			for s in nameComp:
				if len(name.strip()) == 0:
					name = s
					pos = name.find("@")
					if pos >= 0:
						name = name[0 : pos]

			dic[name] = subfix
		elif os.path.isdir(itemPath):
			if itemPath[len(itemPath) - 6:] != ".lproj":
				imgfilenames(dic, itemPath)
			elif itemPath == "en.lproj":
				imgfilenames(dic, itemPath)


if __name__=="__main__":
	if len(sys.argv) < 2:
		print 'Usage:\ngenImageMacros.py images_path macro_file_path\n'
		exit()

	dic ={}
	imgDir = sys.argv[1]
	genFile = sys.argv[2]

	imgfilenames(dic, imgDir)
	if len(dic) > 0:
		fp_h = open(genFile + '.h', 'w')
		file_header_commet = '/**\n *\n'
        file_header_commet += ' * This file is autogenerated by runScript.sh\n'
        file_header_commet += ' * Creates image file name resources\n'
        file_header_commet += ' *\n'
        file_header_commet += ' */\n\n\n\n'
        fp_h.write(file_header_commet)

        for key in dic.keys():
        	name = 'S_' + key.upper()
        	fp_h.write('#ifndef ' + name + '\n')
        	fp_h.write('    #define ' + name + ' @"' + key + '"\n')
        	fp_h.write('#endif\n\n')
